{"name": "This test to RESTORE Files from RUBBISH BIN and confirm RESTORED -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\RestoreFileTestStep.py\", line 21, in restore_001_002\n    context.rubbishPage.find_and_restore_files(context.filename)\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\pages\\RubbishBinPage.py\", line 33, in find_and_restore_files\n    self.webloc.find_by_xpath(config['RubbishBinPage']['lnk_restore']).click()\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\lib\\helperLocator.py\", line 16, in find_by_xpath\n    return self._web_driver_wait.until(EC.visibility_of_element_located((By.XPATH, xpath)))\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open Mega Portal", "status": "passed", "start": 1630225200629, "stop": 1630225206169}, {"name": "When login with valid credentials", "status": "passed", "start": 1630225206169, "stop": 1630225216531}, {"name": "Then it navigates to FileManager successfully", "status": "passed", "start": 1630225216531, "stop": 1630225216906}, {"name": "Given Restore text file with filename as a.txt in Rubbish Bin", "status": "passed", "start": 1630225216907, "stop": 1630225217107}, {"name": "When Search AND RESTORE the file from RUBBISH Bin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\RestoreFileTestStep.py\", line 21, in restore_001_002\n    context.rubbishPage.find_and_restore_files(context.filename)\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\pages\\RubbishBinPage.py\", line 33, in find_and_restore_files\n    self.webloc.find_by_xpath(config['RubbishBinPage']['lnk_restore']).click()\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\lib\\helperLocator.py\", line 16, in find_by_xpath\n    return self._web_driver_wait.until(EC.visibility_of_element_located((By.XPATH, xpath)))\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1630225217108, "stop": 1630225263096}, {"name": "Then it should be RESTORED to FILE_MANAGER successfully", "status": "skipped", "start": 1630225263105, "stop": 1630225263105}], "parameters": [{"name": "filename", "value": "a.txt"}], "start": 1630225193065, "stop": 1630225263105, "uuid": "98a77e23-0ee3-479a-acb1-38412058df1e", "historyId": "fd88b96451ac2fa24783c70f763e50c9", "fullName": "Test file restore features: This test to RESTORE Files from RUBBISH BIN and confirm RESTORED", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Chrome"}, {"name": "tag", "value": "Firefox"}, {"name": "feature", "value": "Test file restore features"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}