{"name": "This test to create a text file and saves successfully -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class=\"close-btn\" aria-label=\"[[close dialog]]\">...</button> is not clickable at point (914, 18). Other element would receive the click: <div class=\"dark-overlay white\"></div>\n  (Session info: MicrosoftEdge=92.0.902.84)\n\n", "trace": "  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CreateFileTeststeps.py\", line 49, in Test_case_001_01\n    context.file_manage.write_text_and_save(context.Test_text)\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\pages\\FileManagerPage.py\", line 65, in write_text_and_save\n    close_cross_button.click()\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open Mega Portal", "status": "passed", "start": 1630229216287, "stop": 1630229226091}, {"name": "When login with valid credentials", "status": "passed", "start": 1630229226092, "stop": 1630229235722}, {"name": "Then it navigates to FileManager successfully", "status": "passed", "start": 1630229235722, "stop": 1630229242906}, {"name": "Given create a text file with filename as a.txt", "status": "passed", "start": 1630229242906, "stop": 1630229245274}, {"name": "When add text as megatesting", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class=\"close-btn\" aria-label=\"[[close dialog]]\">...</button> is not clickable at point (914, 18). Other element would receive the click: <div class=\"dark-overlay white\"></div>\n  (Session info: MicrosoftEdge=92.0.902.84)\n\n", "trace": "  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CreateFileTeststeps.py\", line 49, in Test_case_001_01\n    context.file_manage.write_text_and_save(context.Test_text)\n  File \"C:\\Users\\senthilk\\Documents\\MegaTest\\pages\\FileManagerPage.py\", line 65, in write_text_and_save\n    close_cross_button.click()\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\senthilk\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1630229245274, "stop": 1630229258425}, {"name": "Then it save the text file successfully", "status": "skipped", "start": 1630229258438, "stop": 1630229258438}], "parameters": [{"name": "filename", "value": "a.txt"}, {"name": "Test_text", "value": "megatesting"}], "start": 1630229203360, "stop": 1630229258438, "uuid": "af76771a-d6a8-41c8-849d-373fce057973", "historyId": "5cdc33f53a6caca8c0416c5ed55405cc", "fullName": "Test file creation features: This test to create a text file and saves successfully", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Chrome"}, {"name": "tag", "value": "Firefox"}, {"name": "feature", "value": "Test file creation features"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}